---
on:
  push:

jobs:
  container-project:
    name: Container Project
    uses: DarylStark/slough-gha-wf-container-projects/.github/workflows/workflow.yml@issue-10/feature/new-workflows
    with:
      enable-ci: true
      enable-cd: ${{ github.ref_name == 'main' }}
