---
on:
  push:

jobs:

  container-project-workflow:
    name: Container Project
    uses: DarylStark/slough-gha-wf-container-projects/.github/workflows/workflow.yml@issue-10/feature/new-workflows
    with:
      enable-ci: true
      enable-cd: ${{ github.ref_name == 'main' || github.ref_name == 'dev' }}
      container-tags: ${{ needs.generate-tags.outputs.tags }}
      container-repository: dast1986
      version: 1.0.0
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
